version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: event-manager-db
    restart: unless-stopped

    environment:
      POSTGRES_DB: event-manager-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

    ports:
      - "5432:5432"